/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    WdButton: typeof import('@wot-ui/ui/components/wd-button/wd-button.vue')['default']
    WdEmpty: typeof import('@wot-ui/ui/components/wd-empty/wd-empty.vue')['default']
    WdIcon: typeof import('@wot-ui/ui/components/wd-icon/wd-icon.vue')['default']
    WdInput: typeof import('@wot-ui/ui/components/wd-input/wd-input.vue')['default']
    WdInputNumber: typeof import('@wot-ui/ui/components/wd-input-number/wd-input-number.vue')['default']
    WdLoading: typeof import('@wot-ui/ui/components/wd-loading/wd-loading.vue')['default']
    WdNavbar: typeof import('@wot-ui/ui/components/wd-navbar/wd-navbar.vue')['default']
    WdPopup: typeof import('@wot-ui/ui/components/wd-popup/wd-popup.vue')['default']
    WdSignature: typeof import('@wot-ui/ui/components/wd-signature/wd-signature.vue')['default']
    WdTag: typeof import('@wot-ui/ui/components/wd-tag/wd-tag.vue')['default']
    WdToast: typeof import('@wot-ui/ui/components/wd-toast/wd-toast.vue')['default']
  }
}
